language: go
sudo: required
services:
- docker
go : '1.10'
cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/vendor
after_success: |
  bash <(curl -s https://codecov.io/bash)

  if [ "${TRAVIS_BRANCH}" == "master" ]; then
    make docker-push
    curl -s -X POST https://goreportcard.com/checks?repo=github.com/ViBiOh/fibr

    sed \
      -e "s|\${DATA_DIR}|${DATA_DIR}|g" \
      -e "s|\${DATA_USER_ID}|${DATA_USER_ID}|g" \
      -e "s|\${BASIC_USERS}|${BASIC_USERS}|g" \
      -e "s|\${VERSION}|${TRAVIS_COMMIT}|g" \
      docker-compose.yml > docker-compose-env.yml
  fi
notifications:
  email: false
deploy:
  provider: script
  skip_cleanup: true
  script: "curl -H 'Authorization: GitHub ${GITHUB_OAUTH_TOKEN}' -X POST https://dashboard-api.vibioh.fr/containers/fibr/ --data-binary @docker-compose-env.yml"
  on:
    branch: master
