language: go
sudo: required
services:
- docker
go: 1.9
after_success: |
  bash <(curl -s https://codecov.io/bash)

  if [ "${TRAVIS_BRANCH}" == "master" ]; then
    make docker-push

    sed \
      -e "s|\${DATA_DIR}|${DATA_DIR}|g" \
      docker-compose.yml > docker-compose-env.yml
  fi
notifications:
  email: false
deploy:
  provider: script
  skip_cleanup: true
  script: "curl -H 'Authorization: GitHub ${GITHUB_OAUTH_TOKEN}' -X POST https://dashboard-api.vibioh.fr/containers/fibr/ --data-binary @docker-compose-env.yml"
  on:
    branch: master
