---
version: "3.9"

services:
  service:
    image: vibioh/fibr
    environment:
      FIBR_AUTH_USERS: "${BASIC_USERS}"
      FIBR_AMQP_URI: "amqp://guest:guest@rabbit:5672/"
      FIBR_AMQP_WAIT_TIMEOUT: "30s"
      FIBR_CHUNK_UPLOAD: "true"
      FIBR_EXIF_DIRECT_ACCESS: "true"
      FIBR_REDIS_ADDRESS: redis:6379
      FIBR_THUMBNAIL_DIRECT_ACCESS: "true"
    ports:
      - "1080:1080/tcp"
    volumes:
      - "${DATA_DIR}:/data"
      - "/tmp:/tmp"
    entrypoint:
      - /wait
      - -timeout
      - 30s
      - -address
      - tcp:rabbit:5672
      - -address
      - tcp:redis:6379
      - -next
      - /fibr
    depends_on:
      - redis
      - rabbit
    user: "${DATA_USER_ID}"
    read_only: true

  redis:
    image: redis
    read_only: true

  rabbit:
    image: rabbitmq:3-alpine

  image:
    image: h2non/imaginary

  exas:
    image: vibioh/exas
    environment:
      EXAS_AMQP_URI: "amqp://guest:guest@rabbit:5672/"
      EXAS_AMQP_WAIT_TIMEOUT: "30s"
      EXAS_GEOCODE_URL: "https://nominatim.openstreetmap.org"
      EXAS_STORAGE_FILE_SYSTEM_DIRECTORY: "/data"
    volumes:
      - "${DATA_DIR}:/data"
    entrypoint:
      - /wait
      - -timeout
      - 30s
      - -address
      - tcp:service:1080
      - -next
      - /exas
    depends_on:
      - rabbit
    user: "${DATA_USER_ID}"
    read_only: true

  vignet:
    image: vibioh/vignet
    environment:
      VIGNET_AMQP_URI: "amqp://guest:guest@rabbit:5672/"
      VIGNET_AMQP_WAIT_TIMEOUT: "30s"
      VIGNET_STORAGE_FILE_SYSTEM_DIRECTORY: "/data"
    volumes:
      - "${DATA_DIR}:/data"
    entrypoint:
      - /wait
      - -timeout
      - 30s
      - -address
      - tcp:service:1080
      - -next
      - /vignet
    depends_on:
      - rabbit
      - image
    user: "${DATA_USER_ID}"
    read_only: true
