---
version: '3.9'

services:
  service:
    image: vibioh/fibr
    environment:
      FIBR_AUTH_USERS: '${BASIC_USERS}'
      FIBR_AMQP_URI: 'amqp://guest:guest@rabbit/fibr'
      FIBR_AMQP_WAIT_TIMEOUT: '30s'
      FIBR_CHUNK_UPLOAD: 'true'
      FIBR_EXIF_DIRECT_ACCESS: 'true'
      FIBR_REDIS_ADDRESS: redis:6379
      FIBR_THUMBNAIL_DIRECT_ACCESS: 'true'
    ports:
      - '1080:1080/tcp'
    volumes:
      - '${DATA_DIR}:/data'
      - '/tmp:/tmp'
    depends_on:
      - redis
      - rabbit
      - exas
      - vith
    user: '${DATA_USER_ID}'
    read_only: true

  redis:
    image: redis
    read_only: true

  rabbit:
    image: rabbitmq:3-alpine
    environment:
      RABBITMQ_DEFAULT_VHOST: fibr

  exas:
    image: vibioh/exas
    environment:
      EXAS_AMQP_URI: 'amqp://guest:guest@rabbit/fibr'
      EXAS_AMQP_WAIT_TIMEOUT: '30s'
      EXAS_GEOCODE_URL: 'https://nominatim.openstreetmap.org'
      EXAS_STORAGE_FILE_SYSTEM_DIRECTORY: '/data'
    volumes:
      - '${DATA_DIR}:/data'
    depends_on:
      - rabbit
    user: '${DATA_USER_ID}'
    read_only: true

  vith:
    image: vibioh/vith
    environment:
      VITH_AMQP_URI: 'amqp://guest:guest@rabbit/fibr'
      VITH_AMQP_WAIT_TIMEOUT: '30s'
      VITH_STORAGE_FILE_SYSTEM_DIRECTORY: '/data'
    volumes:
      - '${DATA_DIR}:/data'
    depends_on:
      - rabbit
      - image
    user: '${DATA_USER_ID}'
    read_only: true

  image:
    image: h2non/imaginary
