---
version: '2.1'

services:
  site:
    image: vibioh/fibr
    environment:
      FIBR_AUTH_PROFILES: 1:admin
      FIBR_AUTH_USERS: '${BASIC_USERS}'
      FIBR_IGNORE_PATTERN: '.st(folder|ignore)'
      FIBR_LOGGER_JSON: 'true'
      FIBR_EXIF_DIRECT_ACCESS: 'true'
      FIBR_THUMBNAIL_DIRECT_ACCESS: 'true'
      FIBR_EXIF_MAX_SIZE: '0'
      FIBR_THUMBNAIL_MAX_SIZE: '0'
    volumes:
      - ${DATA_DIR}:/data
    depends_on:
      - image
      - video
      - exas
    user: '${DATA_USER_ID}'
    restart: on-failure:5
    read_only: true

  image:
    image: h2non/imaginary
    restart: on-failure:5
    read_only: true

  video:
    image: vibioh/vith
    environment:
      VITH_LOGGER_JSON: 'true'
      VITH_WORK_DIR: '/data'
    volumes:
      - ${DATA_DIR}:/data
    user: '${DATA_USER_ID}'
    restart: on-failure:5

  exas:
    image: vibioh/exas
    environment:
      EXAS_LOGGER_JSON: 'true'
      EXAS_WORK_DIR: '/data'
    volumes:
      - ${DATA_DIR}:/data
    user: '${DATA_USER_ID}'
    restart: on-failure:5
