---
version: '2.1'

services:
  site:
    image: vibioh/fibr
    environment:
      FIBR_AUTH_PROFILES: 1:admin
      FIBR_AUTH_USERS: '${BASIC_USERS}'
      FIBR_IGNORE_PATTERN: '.st(folder|ignore)'
      FIBR_LOGGER_JSON: 'true'
    volumes:
      - ${DATA_DIR}:/data
    depends_on:
      - image
      - video
    user: '${DATA_USER_ID}'
    restart: on-failure:5
    read_only: true

  video:
    image: vibioh/vith
    environment:
      VITH_LOGGER_JSON: 'true'
    restart: on-failure:5

  image:
    image: h2non/imaginary
    restart: on-failure:5
    read_only: true

  exas:
    image: vibioh/exas
    environment:
      EXAS_LOGGER_JSON: 'true'
    restart: on-failure:5
    read_only: true
