---
version: '2.1'

services:
  site:
    image: vibioh/fibr
    environment:
      FIBR_AUTH_PROFILES: 1:admin
      FIBR_AUTH_USERS: '${BASIC_USERS}'
      FIBR_EXIF_DIRECT_ACCESS: 'true'
      FIBR_THUMBNAIL_DIRECT_ACCESS: 'true'
    ports:
      - 1080:1080/tcp
    volumes:
      - ${DATA_DIR}:/data
    depends_on:
      - image
      - vith
      - exas
    user: '${DATA_USER_ID}'
    restart: on-failure:5
    read_only: true

  vith:
    image: vibioh/vith
    environment:
      VITH_WORK_DIR: '/data'
    volumes:
      - ${DATA_DIR}:/data
    user: '${DATA_USER_ID}'
    restart: on-failure:5

  image:
    image: h2non/imaginary
    restart: on-failure:5
    read_only: true

  exas:
    image: vibioh/exas
    environment:
      EXAS_WORK_DIR: '/data'
    volumes:
      - ${DATA_DIR}:/data
    user: '${DATA_USER_ID}'
    restart: on-failure:5
