---
version: '2.1'

services:
  service:
    image: vibioh/fibr
    environment:
      FIBR_AUTH_USERS: '${BASIC_USERS}'
      FIBR_EXIF_DIRECT_ACCESS: 'true'
      FIBR_THUMBNAIL_DIRECT_ACCESS: 'true'
      FIBR_REDIS_ADDRESS: redis:6379
    ports:
      - '1080:1080/tcp'
    volumes:
      - ${DATA_DIR}:/data
    depends_on:
      - image
      - vith
      - exas
    user: '${DATA_USER_ID}'
    restart: on-failure
    read_only: true

  redis:
    image: redis
    restart: on-failure
    read_only: true

  vith:
    image: vibioh/vith
    environment:
      VITH_STORAGE_FILE_SYSTEM_DIRECTORY: '/data'
    volumes:
      - ${DATA_DIR}:/data
    user: '${DATA_USER_ID}'
    restart: on-failure

  image:
    image: h2non/imaginary
    restart: on-failure
    read_only: true

  exas:
    image: vibioh/exas
    environment:
      EXAS_STORAGE_FILE_SYSTEM_DIRECTORY: '/data'
      EXAS_GEOCODE_URL: 'https://nominatim.openstreetmap.org'
    volumes:
      - ${DATA_DIR}:/data
    user: '${DATA_USER_ID}'
    restart: on-failure
