---
version: '2.1'

services:
  service:
    image: vibioh/fibr
    environment:
      FIBR_AMQP_URI: amqp://amqp:6572/
      FIBR_AUTH_USERS: '${BASIC_USERS}'
      FIBR_CHUNK_UPLOAD: 'true'
      FIBR_EXIF_DIRECT_ACCESS: 'true'
      FIBR_REDIS_ADDRESS: redis:6379
      FIBR_THUMBNAIL_DIRECT_ACCESS: 'true'
    ports:
      - '1080:1080/tcp'
    volumes:
      - ${DATA_DIR}:/data
      - /tmp:/tmp
    depends_on:
      - redis
      - amqp
      - exas
      - vith
    user: '${DATA_USER_ID}'
    restart: on-failure
    read_only: true

  redis:
    image: redis
    restart: on-failure
    read_only: true

  amqp:
    image: rabbitmq:management
    ports:
      - '15672:15672/tcp'
    restart: on-failure

  exas:
    image: vibioh/exas
    environment:
      EXAS_AMQP_URI: 'amqp://amqp:6572/'
      EXAS_GEOCODE_URL: 'https://nominatim.openstreetmap.org'
      EXAS_STORAGE_FILE_SYSTEM_DIRECTORY: '/data'
    volumes:
      - ${DATA_DIR}:/data
    user: '${DATA_USER_ID}'
    restart: on-failure

  vith:
    image: vibioh/vith
    environment:
      VITH_AMQP_URI: 'amqp://amqp:6572/'
      VITH_STORAGE_FILE_SYSTEM_DIRECTORY: '/data'
    volumes:
      - ${DATA_DIR}:/data
    depends_on:
      - image
    user: '${DATA_USER_ID}'
    restart: on-failure

  image:
    image: h2non/imaginary
    restart: on-failure
