---
version: '2.1'

services:
  image:
    image: h2non/imaginary
    labels:
      traefik.http.routers.imaginary-http.rule: Host(`imaginary.vibioh.fr`)
      traefik.http.routers.imaginary-http.entrypoints: http
      traefik.http.routers.imaginary-http.middlewares: ratelimit@file, redirect@file
      traefik.http.routers.imaginary-https.rule: Host(`imaginary.vibioh.fr`)
      traefik.http.routers.imaginary-https.entrypoints: https
      traefik.http.routers.imaginary-https.middlewares: ratelimit@file, compress@file
      traefik.http.routers.imaginary-https.tls: 'true'
      traefik.http.routers.imaginary-https.tls.certresolver: default
      traefik.http.services.imaginary-service.loadbalancer.server.port: '9000'
    restart: on-failure:5
    read_only: true
    security_opt:
      - no-new-privileges
