version: '2'

services:
  static:
    image: vibioh/fibr-static
    command:
    - -tls
    labels:
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.rule: 'Host: fibr-static.vibioh.fr'
      traefik.protocol: 'https'
      traefik.port: '1080'
      traefik.frontend.rateLimit.extractorFunc: 'client.ip'
      traefik.frontend.rateLimit.rateSet.first.period: '60s'
      traefik.frontend.rateLimit.rateSet.first.average: '100'
      traefik.frontend.rateLimit.rateSet.first.burst: '200'
    logging:
      driver: json-file
      options:
        max-size: '10m'
    restart: on-failure:5
    read_only: true
    cpu_shares: 128
    mem_limit: 67108864
    security_opt:
    - no-new-privileges

  site:
    image: vibioh/fibr
    command:
    - -tls
    - -authUsers
    - vibioh:admin
    - -basicUsers
    - ${BASIC_USERS}
    - -version
    - ${VERSION}
    - -csp
    - default-src 'self'; base-uri 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' fibr-static.vibioh.fr
    labels:
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.rule: 'Host: fibr.vibioh.fr'
      traefik.protocol: 'https'
      traefik.port: '1080'
      traefik.frontend.rateLimit.extractorFunc: 'client.ip'
      traefik.frontend.rateLimit.rateSet.first.period: '60s'
      traefik.frontend.rateLimit.rateSet.first.average: '100'
      traefik.frontend.rateLimit.rateSet.first.burst: '200'
    volumes:
    - ${DATA_DIR}:/data
    user: '1000'
    logging:
      driver: json-file
      options:
        max-size: '10m'
    restart: on-failure:5
    read_only: true
    cpu_shares: 128
    mem_limit: 536870912
    security_opt:
    - no-new-privileges

networks:
  default:
    external:
      name: traefik
