[[constraint]]
  branch = "master"
  name = "github.com/ViBiOh/auth"

[[constraint]]
  branch = "master"
  name = "github.com/ViBiOh/httputils"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[prune]
  go-tests = true
  unused-packages = true
