apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: custom-local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fibr
  namespace: default
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: custom-local-storage
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /home/vibioh/Documents
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - delta
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fibr
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: custom-local-storage
  resources:
    requests:
      storage: 30Gi
