apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fibr
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: '0.0.79'
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: fibr
    image:
      name: vibioh/fibr
      tag: '202202021653' # {"$imagepolicy": "default:flux-fibr-web:tag"}
    volumes:
      - name: data
        persistentVolumeClaim:
          claimName: fibr
    volumeMounts:
      - name: data
        mountPath: /data
    config:
      FIBR_AUTH_PROFILES: 1:admin
      FIBR_EXIF_DIRECT_ACCESS: 'true'
      FIBR_EXIF_URL: http://exas
      FIBR_IGNORE_PATTERN: '.st(folder|ignore)'
      FIBR_LOGGER_JSON: 'true'
      FIBR_SANITIZE_ON_START: 'true'
      FIBR_THUMBNAIL_DIRECT_ACCESS: 'true'
      FIBR_THUMBNAIL_MIN_BITRATE: '30000000'
      FIBR_THUMBNAIL_URL: http://vith
      FIBR_PUBLIC_URL: https://fibr.vibioh.fr
    secrets:
      FIBR_AUTH_USERS: AgDRNDt2lewmiDehsMHqXT1TEoLAcoovsPgFli2MisOFJBteY8aO9XCtQSxz8Kw/t0enClbdJmdX+vo60SstVzXwZQaAD+FeD3nCD9CXXhK05Izm8bXbw+ZQgvP6Ne5U6ljLR4AUJrNqzu+wf07I5jiDc3wkdH9Ka8CrBKcpG587q9DwQxW9kgPKC70FfBZfz7TYyxbaQIytHA+8oZTnov7QaZ7qVPIbDWH0XDXNOB+DSoSY4W/Nkl4pCBDqCiwn+FH1PaDorD8MO733nzaOuYPBovmzv47AUaHxVJWQADDjkrmzynApuPjZ2ZYzOZmO419/7sN2uzllDfuDCXk4+TuR1ETKuAHnDQLVewafm5K1mCr78+K+WH1bynX2MKzYAISOGJsJOYD+E4eJqOZmTbPBbnpPQzQgzyjzLBTp9KAwUpjq991JrepPAQ4FOmLDrsLszN/Sgh9G8JL1N0X25Rs/Mp5Kjr1NTkXFLRfF22oxDn08oe4V8Qcw1IbSwRg+vNQ5SXPTKEfkaHNp04FeozQlVgMbeGnQ1mgU8Ubc/cR2C/+pdGbtWDN0XQHzpwABkxCT5WwyOZlMScezM7qqFb+XgBZ7J8a6XA8bbRn/zjcSRkbjcHSy43whbq7/Wu7KO/R9Lc7+LA4U/9OwBok+AJKQyEt3fzxB+utpeAtUj5zRJJodxJYbuwnR+hb15w4RXhmiL1oFU25aVEm/RDkPE1hXX9rz/Crw5ymWcGRdV3fKLi8qVsVSlWUC7OAKmLADT5U+TBH3jcs1DcPGRCVsTrMJ43uXaCU=
      FIBR_WEBHOOK_SECRET: AgA+IehgCXeyN6Odu8CzwQp46t4ZASL5xUvoVXRvEcR9U7sIU9oKfQkII6Vm4XVuB5NqJOqBdZrUmb2iBqwu1jx8cC4w11QWLOb3fYc2SMXkJDvNnZ9xBmN92TEHLzqx/Yfrre/BJKDbqMMu+yPxSZ2JiW1AKYN6eD2w37E0dtxHP9tJ59T6s2EtyM08xL/54pahPflPU5VIs9ThG3+5n2IeWURhhcOZufeE1JKbPdNj+ngJ3I0aPnT0GyUCp8tvowFQvlvNlZO99rO6l1xKMQJunVg9xZ0iGf3VbZYjc9dfQ+zLYAkl7a5L6AWqdHw2N6hhp78gP4o/QVy8SIRMZmEGpBA8tDm0O94tJPpX8xArT3h6t/Frh5icUNaZjdrTQ43foMx4kbTyjI/52L34beoF65tdMDMziyZdBLssWmlX1vVyz/jt178M6wi6PErMPIAfU7SXiTo2Ee243VGrXpNfEMrSiExsEurQGy97ixOH4uhVKEAwOyzjHaZocFhtp94eGGS6H8u3/hhm4dq0AM8s4+vA9IrWprPKYo0NXAunOhE8+enaOZH+tz/vSXb6FzT1efA7g63blB4PDPj0Srg8MbTXQeFqchcSHziWOQ6GPtAsZHRzkDP0E8/zP3A8sOwB2QLdkX/arPbw4wJZvlt09Efl8WnjMDrikr06Fe/OFU5oslrkgLuJK3ayHZ6w/d9ZaNvjv2DCU7LTWMNHZE/YjeDXRJpAD+hWrrlqvSOlhh3uyzjOqex99NJmixEqfqL053Mt83caxUhABtGRldNO3ZMBP+qmUrtkc8plGkvRbpdf0Qe22auUGVMqQRk7
      FIBR_AMQP_URI: AgDF7C2kfoe/MyLRTjIiPvxeSZrWcOCfEpDya6Je2RP6ozAhLSFFNrudBZeFrNuOrssngREGVwVbavGEuPOouqVtKqGhSIEtgc1n9/Nq04SWROITEpNwHgexdu3TYRYKNaQQnXfljuFm+AhVR8rorenUYVsjT/b586RIbbHD51JobR9O5Qtk/UIVi6TUCFLsT2LfrCuMfBN7xuroRDnHQdacOY41pj6CSAk5xPpc9llA7JQbiuOM2oJSf3RMBsvyE8XnV8PyuzS/16q92W5y72UPPrcBS17RVMPHFkkOR9i+Eo/NBtkeCn2wKZg+o6YlJT5GnJJMJ/hIYb6r6SAq6iR9OaCn4la1oCIApdt8SwNDCFox402aoFFwIoFKHadqpV1Wgy7WRR9Nza6qWv069esh7Gc8il6zAxP1/2aqN1tc4j7H6+iJpGkxvux7et1haoD1DMa685H4q+7bTldrLBKm2lHuVaQLfE9n+FUtXriydr9gR15f/jaHgeB8y90upl7oUcajGEFjDHQCRFXFdo8j29mtfq90nol9zJSKpQWHpV7q7Q+q2v4KF/zsVUlhUsLgndcM887RwELoCAHvdcWKyhpyIe0PjRhO/jks4HJcKw9d96CAsFd+LiGst85XEC0dW950LzTc+Oi8bcas0geizpQtBvobviQBjuaXIzOcvg41l8F7UYancQuidcQpInEG7SzoMWo8fD+M3WUzrpXavXZv06zVbI2ls6OjdFflYJORU+ntmVrvP7Wdt2TlZXQddtE=
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - delta
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/storage
        operator: Exists
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 400m
        memory: 64Mi
    securityContext:
      runAsGroup: 1000
      runAsUser: 1000
      runAsNonRoot: true
      allowPrivilegeEscalation: false
    autoscaling:
      enabled: false
    ingress:
      enabled: true
      compress: true
      hosts:
        - fibr.vibioh.fr
