apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fibr
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: '0.0.75'
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: fibr
    image:
      name: vibioh/fibr
      tag: '202109232014' # {"$imagepolicy": "default:flux-fibr-web:tag"}
    volumes:
      - name: data
        persistentVolumeClaim:
          claimName: fibr
    volumeMounts:
      - name: data
        mountPath: /data
    config:
      FIBR_AUTH_PROFILES: 1:admin
      FIBR_EXIF_AGGREGATE_ON_START: 'true'
      FIBR_EXIF_DATE_ON_START: 'true'
      FIBR_EXIF_GEOCODE_URL: 'https://nominatim.openstreetmap.org'
      FIBR_EXIF_URL: http://exas
      FIBR_IGNORE_PATTERN: '.st(folder|ignore)'
      FIBR_LOGGER_JSON: 'true'
      FIBR_SANITIZE_ON_START: 'true'
      FIBR_THUMBNAIL_DIRECT_ACCESS: 'true'
      FIBR_THUMBNAIL_IMAGE_URL: https://imaginary.vibioh.fr
      FIBR_THUMBNAIL_MAX_SIZE: '0'
      FIBR_THUMBNAIL_VIDEO_URL: http://vith
      FIBR_THUMBNAIL_MIN_BITRATE: '30000000'
    secrets:
      FIBR_AUTH_USERS: AgAC3NPujqeHIkNIJQ5TLB+OquA+XDy7khc5HOVU/Op4oTRSYlmvmYSk8kyPqU+DLT1MSpOpZrFRYM6da080kvnAVXYHer7o2OikJlXxjyOyRpTDA4cj6Aaew04Vl63mepUn5U+0yhz5LNQSkjl5XbY03xs5Ee+oOp/IgZez0i1d7Q2Gt3aEusunscXdu4ArgvO311kZMZ8JuZhf1rNtf51r0Cw0YCDP21I2HbMFxtGLJ2Z+FVDHAUQu10jkP5OAipIL5E71mqoogGiIdB04X7mot9Yunu0tfwA6FLK50JCkJenraO3c0NG6Io9KoURVMjzPVxL0nqZHmPFgVE3xJIW1WzSnh2BwIHZKj/YwmuEOtFO2i15lksXckGaVdB/2YNuwpQAaQNbDCeE5cH5sQCkK2lu6ia6+wnW/OrgxhvyhMoNyvCqAJC/GYhKGGUcJnrQnLxSmGKt+FJ2tsUVNeMs8itWgdCao7kMiafWHFo5XOSakkTyHD9CJV+OGGCxZRweWWVMP+Qi2nxQBkQNsr4kbqbeFzR1E4fn7Q1I9AGcKvLsuYxyRK2ty691keO57JNS2q5VZLAfjwLwueEJJXCi0cjXU5P7DS9IYqik1qzF5VQhsNUTK1n2m9bzRTXgAX5oq/1H4NUbv6l71uRWFvSbgCNIECZ0GeZ9cKW5hKku/y8nIVGFYBh1Er6Cm/SgChOtFPrugKj7Vbgecn8+e9Up3izO6wUzgw7tO8w/313KxHgNeQlxLXqpnLsdw//lNzfSf1fO6W2o3NIPUXce8EdShBHD8tIw=
      FIBR_WEBHOOK_SECRET: AgA+IehgCXeyN6Odu8CzwQp46t4ZASL5xUvoVXRvEcR9U7sIU9oKfQkII6Vm4XVuB5NqJOqBdZrUmb2iBqwu1jx8cC4w11QWLOb3fYc2SMXkJDvNnZ9xBmN92TEHLzqx/Yfrre/BJKDbqMMu+yPxSZ2JiW1AKYN6eD2w37E0dtxHP9tJ59T6s2EtyM08xL/54pahPflPU5VIs9ThG3+5n2IeWURhhcOZufeE1JKbPdNj+ngJ3I0aPnT0GyUCp8tvowFQvlvNlZO99rO6l1xKMQJunVg9xZ0iGf3VbZYjc9dfQ+zLYAkl7a5L6AWqdHw2N6hhp78gP4o/QVy8SIRMZmEGpBA8tDm0O94tJPpX8xArT3h6t/Frh5icUNaZjdrTQ43foMx4kbTyjI/52L34beoF65tdMDMziyZdBLssWmlX1vVyz/jt178M6wi6PErMPIAfU7SXiTo2Ee243VGrXpNfEMrSiExsEurQGy97ixOH4uhVKEAwOyzjHaZocFhtp94eGGS6H8u3/hhm4dq0AM8s4+vA9IrWprPKYo0NXAunOhE8+enaOZH+tz/vSXb6FzT1efA7g63blB4PDPj0Srg8MbTXQeFqchcSHziWOQ6GPtAsZHRzkDP0E8/zP3A8sOwB2QLdkX/arPbw4wJZvlt09Efl8WnjMDrikr06Fe/OFU5oslrkgLuJK3ayHZ6w/d9ZaNvjv2DCU7LTWMNHZE/YjeDXRJpAD+hWrrlqvSOlhh3uyzjOqex99NJmixEqfqL053Mt83caxUhABtGRldNO3ZMBP+qmUrtkc8plGkvRbpdf0Qe22auUGVMqQRk7
      FIBR_THUMBNAIL_IMAGE_USER: AgC9eQhErqPt8uZkUMyVybXuPVJXJu71HHQ6X2ksEB3BRJBBrwlpawFMR7glAmYki2C0fwtGLhFmx/T9Se2ahT1+UtvbwihmyZI0qlx8QhVOW548LcVXrcf85u2/KdHnZe3RL7p5QAiCYY9g3xuCgznem1XDBrPirdPWu3jFc92XdKo8Yova7jL/6Ln3lYWLSqPKbnI02krPkcJg1Thrdsdpn7cnByuQjJOj2/FQeCJAgmF0t8SgcG2u/PwLT9hcS9Kq692PS7GU9XEGXsjFl5YCwYjDdAZMvwzR/l4br+I112lEKy8B5xUhL4X/b1b1H9mw/ll5OwoWZTTQ9dstMzqBsftBOQCcr7GhwScDMB7DEEMycAAkA9x9qeA2CAywbIA1zMuNlAPx+1TIoQpGJp64C9q+/dViecgTwbCxWLQZ8u5Y8EqTOXyHrbjs1y9vX+17wjPlgpG+j1A75NxripaGz+9tWwAyicw1owqe5VYNF0DdA7lpqXeBBazw8A4so/rgouD+8vO9CeCZbJRQ1rGMfVq7c4rIMH7ABPgnlHeLnX683Tn3LtR6c/4TBoCHuNM6EKebP+mpCshYJ2pKcC1yMb+sx8Coe3X0iNYlZEZ5vgufqiEhOipB6XA+3EWp6ugOBaN5WYeO+ZeQzJweOBKhWFSdlXLePvfsHk8+iOqponb5nQIq/yLqTJqdHNUsLrAa9pVF6r4=
      FIBR_THUMBNAIL_IMAGE_PASSWORD: AgCc5QaW6JYVWiEavKCLfpHwfta05crpcv4QkIH9gICFARI5WwMpkd/3AzHa1fvVSH6Rf016KtdYveF71uKKeiLKvK6ulIDCk9ToTgkO9XnjPzKQFSfn05NVJbpZoVgp+59/M7kKQbDUU+x9pZyhThvy1++FMH5RP9+3MPSJz2Wi3dwsRonj/SykuYDzkdtXjNSZ/smzsL2SMW/AemvIDY205MBaiZKqVJE5ayPl9ZNmXmytzHwBXtzxM6F3sdkK3cQ3qiBfh3vMZoCGys6UgML+eqv6G5IbjXtSUdZWnorY8D1vAyd0o+JYnIZo3mm8sZLmHv2Z2LqrpckLSeq5RFSF652mfls06wiEeZza3NLA5XG71Qt4TXhU1/PhWWCvVFhsmoI84SQLPo1fEWQ75uBgWNjLWFIHMv3+ocfhP0kDqALe+pWORaq8fWzO161xcGc2lbN1jmZVThs3xY2y1iStoTfOuXD4gwrprxco9k+Q4D+39z67rq5vz9Cd302ApUXSSnM7JdjIXi6uOyTOqfnPRGPOiSGMG+bs52PxnrGdjjIyONWMzPfZt+gZJmAK9eifjW079GC97PQJ4aqQQAqkpG2W7A1j/gjts7zXuacIQ9FY4ti3TecWUR52Q/vRMEopsC13FVkgHmBG9Lgzs1ksYUlYzKLMJigHx24FZGsBejhestQGB2vqric8qZFsA2NSwVJfKvqNAB9ThLm10IN64KKdRtL0Z6IbB6sF3Xy6b2sLTH+zhnf/W98cIFoNKs3AEEU+Osxrvocc+ZI=
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - bob
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 400m
        memory: 64Mi
    securityContext:
      runAsGroup: 995
      runAsUser: 999
      runAsNonRoot: true
      allowPrivilegeEscalation: false
    autoscaling:
      enabled: false
    ingress:
      enabled: true
      compress: true
      hosts:
        - fibr.vibioh.fr
