apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fibr
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: '0.0.75'
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: fibr
    image:
      name: vibioh/fibr
      tag: '202110312010' # {"$imagepolicy": "default:flux-fibr-web:tag"}
    volumes:
      - name: data
        persistentVolumeClaim:
          claimName: fibr
    volumeMounts:
      - name: data
        mountPath: /data
    config:
      FIBR_AUTH_PROFILES: 1:admin
      FIBR_EXIF_AGGREGATE_ON_START: 'true'
      FIBR_EXIF_DATE_ON_START: 'true'
      FIBR_EXIF_GEOCODE_URL: 'https://nominatim.openstreetmap.org'
      FIBR_EXIF_URL: http://exas
      FIBR_IGNORE_PATTERN: '.st(folder|ignore)'
      FIBR_LOGGER_JSON: 'true'
      FIBR_SANITIZE_ON_START: 'true'
      FIBR_THUMBNAIL_DIRECT_ACCESS: 'true'
      FIBR_THUMBNAIL_MAX_SIZE: '0'
      FIBR_THUMBNAIL_VIDEO_URL: http://vith
      FIBR_THUMBNAIL_MIN_BITRATE: '30000000'
    secrets:
      FIBR_AUTH_USERS: AgAC3NPujqeHIkNIJQ5TLB+OquA+XDy7khc5HOVU/Op4oTRSYlmvmYSk8kyPqU+DLT1MSpOpZrFRYM6da080kvnAVXYHer7o2OikJlXxjyOyRpTDA4cj6Aaew04Vl63mepUn5U+0yhz5LNQSkjl5XbY03xs5Ee+oOp/IgZez0i1d7Q2Gt3aEusunscXdu4ArgvO311kZMZ8JuZhf1rNtf51r0Cw0YCDP21I2HbMFxtGLJ2Z+FVDHAUQu10jkP5OAipIL5E71mqoogGiIdB04X7mot9Yunu0tfwA6FLK50JCkJenraO3c0NG6Io9KoURVMjzPVxL0nqZHmPFgVE3xJIW1WzSnh2BwIHZKj/YwmuEOtFO2i15lksXckGaVdB/2YNuwpQAaQNbDCeE5cH5sQCkK2lu6ia6+wnW/OrgxhvyhMoNyvCqAJC/GYhKGGUcJnrQnLxSmGKt+FJ2tsUVNeMs8itWgdCao7kMiafWHFo5XOSakkTyHD9CJV+OGGCxZRweWWVMP+Qi2nxQBkQNsr4kbqbeFzR1E4fn7Q1I9AGcKvLsuYxyRK2ty691keO57JNS2q5VZLAfjwLwueEJJXCi0cjXU5P7DS9IYqik1qzF5VQhsNUTK1n2m9bzRTXgAX5oq/1H4NUbv6l71uRWFvSbgCNIECZ0GeZ9cKW5hKku/y8nIVGFYBh1Er6Cm/SgChOtFPrugKj7Vbgecn8+e9Up3izO6wUzgw7tO8w/313KxHgNeQlxLXqpnLsdw//lNzfSf1fO6W2o3NIPUXce8EdShBHD8tIw=
      FIBR_WEBHOOK_SECRET: AgA+IehgCXeyN6Odu8CzwQp46t4ZASL5xUvoVXRvEcR9U7sIU9oKfQkII6Vm4XVuB5NqJOqBdZrUmb2iBqwu1jx8cC4w11QWLOb3fYc2SMXkJDvNnZ9xBmN92TEHLzqx/Yfrre/BJKDbqMMu+yPxSZ2JiW1AKYN6eD2w37E0dtxHP9tJ59T6s2EtyM08xL/54pahPflPU5VIs9ThG3+5n2IeWURhhcOZufeE1JKbPdNj+ngJ3I0aPnT0GyUCp8tvowFQvlvNlZO99rO6l1xKMQJunVg9xZ0iGf3VbZYjc9dfQ+zLYAkl7a5L6AWqdHw2N6hhp78gP4o/QVy8SIRMZmEGpBA8tDm0O94tJPpX8xArT3h6t/Frh5icUNaZjdrTQ43foMx4kbTyjI/52L34beoF65tdMDMziyZdBLssWmlX1vVyz/jt178M6wi6PErMPIAfU7SXiTo2Ee243VGrXpNfEMrSiExsEurQGy97ixOH4uhVKEAwOyzjHaZocFhtp94eGGS6H8u3/hhm4dq0AM8s4+vA9IrWprPKYo0NXAunOhE8+enaOZH+tz/vSXb6FzT1efA7g63blB4PDPj0Srg8MbTXQeFqchcSHziWOQ6GPtAsZHRzkDP0E8/zP3A8sOwB2QLdkX/arPbw4wJZvlt09Efl8WnjMDrikr06Fe/OFU5oslrkgLuJK3ayHZ6w/d9ZaNvjv2DCU7LTWMNHZE/YjeDXRJpAD+hWrrlqvSOlhh3uyzjOqex99NJmixEqfqL053Mt83caxUhABtGRldNO3ZMBP+qmUrtkc8plGkvRbpdf0Qe22auUGVMqQRk7
      FIBR_THUMBNAIL_IMAGE_URL: AgCRO8dB1BEZCMj4tUbyjUiNCvRh21t6AKfO9wiS3WCEGTNXp+f4UKf0sj4ezgP+cc3rlF3/L73Ubaf7bl+srVP+KOJBpb1zEs6V2FN9gy7YSkirqa/X6NYjZ1BSEJjIMJ8iWVeQN4Z2BrXYgCEpzqIbAyFb2lMkwK8m1+5NTNtlZ4Z/Fo7g4QfSf2m4sLZRvQ59YNLReeMSg/d5Cxn0dnMhm5sn9Jn1p90NSsmJjsD4kGI4K0+3SL1MWFTjEJTax378UrxvRkQROluUpfopwiyypdZgCrkkGdkuv7paa/g9olbhVdZeaS6HnVkL1/xvZHCid0WHYPWVHRolwPzzwNOn7ZH8QvM9b/8zEtSLcUzBPEzgvIeY2+mA6OVBd11jQ7xAnX+8AyRVJWYesJJxMOdtjvejtHNu6YR34r6ePYJWh8qkLZ3ZAH+s90tRTVI+1u/ZG6nROthV6w/mDVrOHyFdmEwGcahflmjBFmrIKKopDS2L58s9EkV8er5MaeHcvVzA7/xBgEcaA+4kpskzoIf8G0alE0OrrNLEjxZYMmqIappb73kZqK3SFD0wOIETi7m+nfHTAq+H606jSs3LqmGZuW0OocHvZZO+VKMhKTW16LqS73lEx0IficjafYgNoiwsveeyZidzThDnATq5GvuF1RdMcMfT6ZI+ORxel5wP4w5rAlunOVaL+DTYy/jbhm84tbltnWEuvR2k8SFiVIAZSQgj9KjdlnOuFoN1q1pJw0gG8N5pUzrv11QL9gjY54ex2fRXlwVQ37Bmat11M5M=
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - bob
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 400m
        memory: 64Mi
    securityContext:
      runAsGroup: 995
      runAsUser: 999
      runAsNonRoot: true
      allowPrivilegeEscalation: false
    autoscaling:
      enabled: false
    ingress:
      enabled: true
      compress: true
      hosts:
        - fibr.vibioh.fr
