apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fibr
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: '0.0.71'
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: fibr
    image:
      name: vibioh/fibr
      tag: '202106131035' # {"$imagepolicy": "default:flux-fibr-web:tag"}
    volumes:
    - name: data
      persistentVolumeClaim:
        claimName: fibr
    volumeMounts:
    - name: data
      mountPath: /data
    config:
      FIBR_AUTH_PROFILES: 1:admin
      FIBR_IGNORE_PATTERN: '.st(folder|ignore)'
      FIBR_LOGGER_JSON: 'true'
      FIBR_SANITIZE_ON_START: 'true'
      FIBR_THUMBNAIL_VIDEO_URL: https://vith.vibioh.fr
      FIBR_THUMBNAIL_IMAGE_URL: https://imaginary.vibioh.fr
    secrets:
      FIBR_AUTH_USERS: AgAC3NPujqeHIkNIJQ5TLB+OquA+XDy7khc5HOVU/Op4oTRSYlmvmYSk8kyPqU+DLT1MSpOpZrFRYM6da080kvnAVXYHer7o2OikJlXxjyOyRpTDA4cj6Aaew04Vl63mepUn5U+0yhz5LNQSkjl5XbY03xs5Ee+oOp/IgZez0i1d7Q2Gt3aEusunscXdu4ArgvO311kZMZ8JuZhf1rNtf51r0Cw0YCDP21I2HbMFxtGLJ2Z+FVDHAUQu10jkP5OAipIL5E71mqoogGiIdB04X7mot9Yunu0tfwA6FLK50JCkJenraO3c0NG6Io9KoURVMjzPVxL0nqZHmPFgVE3xJIW1WzSnh2BwIHZKj/YwmuEOtFO2i15lksXckGaVdB/2YNuwpQAaQNbDCeE5cH5sQCkK2lu6ia6+wnW/OrgxhvyhMoNyvCqAJC/GYhKGGUcJnrQnLxSmGKt+FJ2tsUVNeMs8itWgdCao7kMiafWHFo5XOSakkTyHD9CJV+OGGCxZRweWWVMP+Qi2nxQBkQNsr4kbqbeFzR1E4fn7Q1I9AGcKvLsuYxyRK2ty691keO57JNS2q5VZLAfjwLwueEJJXCi0cjXU5P7DS9IYqik1qzF5VQhsNUTK1n2m9bzRTXgAX5oq/1H4NUbv6l71uRWFvSbgCNIECZ0GeZ9cKW5hKku/y8nIVGFYBh1Er6Cm/SgChOtFPrugKj7Vbgecn8+e9Up3izO6wUzgw7tO8w/313KxHgNeQlxLXqpnLsdw//lNzfSf1fO6W2o3NIPUXce8EdShBHD8tIw=
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - bob
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 400m
        memory: 64Mi
    securityContext:
      runAsGroup: 1000
      runAsUser: 1000
      runAsNonRoot: true
      allowPrivilegeEscalation: false
    autoscaling:
      enabled: false
    ingress:
      enabled: true
      hosts:
      - fibr.vibioh.fr
