apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fibr
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: '0.0.81'
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: fibr
    image:
      name: vibioh/fibr
      tag: '202203261155' # {"$imagepolicy": "default:flux-fibr-web:tag"}
    volumes:
    - name: data
      persistentVolumeClaim:
        claimName: fibr
    volumeMounts:
    - name: data
      mountPath: /data
    config:
      FIBR_EXIF_DIRECT_ACCESS: 'true'
      FIBR_EXIF_URL: http://exas
      FIBR_IGNORE_PATTERN: '.st(folder|ignore)'
      FIBR_LOGGER_JSON: 'true'
      FIBR_PUBLIC_URL: https://fibr.vibioh.fr
      FIBR_SANITIZE_ON_START: 'true'
      FIBR_THUMBNAIL_DIRECT_ACCESS: 'true'
      FIBR_THUMBNAIL_LARGE_SIZE: '1000'
      FIBR_THUMBNAIL_MIN_BITRATE: '30000000'
      FIBR_THUMBNAIL_URL: http://vith
      FIBR_TRACER_URL: http://jaeger.monitoring:14268/api/traces
      OTEL_SERVICE_NAME: fibr
    secrets:
      FIBR_AMQP_URI: AgDdfrolM6obLX26aEPVfebLPwcf5Quo0dZR7CByG9DgrSrmqgnyf9kyyPxoB6LBh3swTy4/pTlraMUupv+uwU6q0Cn/Fex1T0DRUratsM2Dfl7nNqqAAjW7hDlJYm6RGPEryLYzuaxEdepgCM0iMUEQA2oHe58/Ug7obEiR52J6ujanaSi7b6FGKB+OaFwIbw0DQI7jaZ/9AMlUftgMdJQnNiRoYAt6UUaYAse1CceoEC/YT6qHAcEcLj1AI8EfiG+fe6AXsKqTU7olQ64ttcLUgy8XTlrFjMi+DHSwYw8zYRc3OfGiIQ125FMlF+BA6obspShpwuWRWiN7+VH4cogYPw5kkhLJAvrsQqVngW5WhQ0gXHyMn6AL4FGu4b8Ylp104rwVNbueL0w0bzJBw53p760ixKXhYkCrp1slfewq079T0CGe/+PnmCTdYRGSzRrNPeYFnLl4O6tnW0ickRfxxk8T+wBKav1a7pW82K/cIlKukggXsq+ZnevuijvKxKTAJ5wpGZAFb6/GV1axAX/tcor525+1Z8P79f04oMn0V7O0+GlcMbXvRnEqHyKB9fCQLB8vINLOWKff1W0WZWBHGboh18yLKlayM28eWg2OvO/m2ve0zna6yzJGz5TWqfwbvi1NDQdAJb47Ck6hufoZSDUz8FiGPWNG78f4ziVQlEHPFYjnQYGu0r7hBmgYqrQ7GfJ6Jfp0uP+Z3jksFgpZ6qhFI425oS9CkR9dI7iX3BTH3q6XTdonddzSP7iw9DiDJE4=
      FIBR_AUTH_USERS: AgBhISCbbs7GM7nbYnH8ybt7l7AAUDRAQV4xcYPMfSi9MwQMbkL8Ndfp7Qi0ma77z+YN4imutOGqlmEhhrzObjkZrFa6ew+yvDTyOADQa24TV3DLjQp3tfyF5bfgodoMALgIEnHe3bT+cN4KURZuj6eeHn1wOK5nOGjrBtuNPF9UpGY/bJT14tbAEfxCJU0WRPH/iH2RT7x9xpKa8FXWmi1uCDM27hnadnZD3a5w4PHHt1JqzUCiRg1KovTWO3D2uGhLf311YqvGBA8XcVZLRD9u5pUwVrpQ1f8o5W6t/ET98SqROIZzNHsEghA0RwtejW+mTJ1yzgl7qa0UUTWW1pMeu8+HPzH7HMlfN66KTNkxRHD8FZdz2Q+W+RB4GAcwF5cx58934FF6VVuLP7omXNf/Sn5k5/mmROcDnid0iB3ZCta3EWDQFbEzyqCbgfpMSw5C8xD2L4JSFn1OuGonEbtGdxORt2JDcpwTcQUjmaVynHsmeNBoZDwPzQHKGMA88rgzFavVnv2Zpvv71VeRtD/cg/5jNSiiATrTcGRTxUVQLecw2c3a5fgVrTmsrsWV8iJwkwCCos62kFXbXeXZEGJbOp4Q3fq7ntZaRfRWyKyrUMJgjco1mg3pkRqvmLJhRduAfp6J+GxYLp7owOoamvmGYeIhqQHR0kb+1MngoH/spt1irnVkSQdcko+q095Hxna9TjseszWh2zno8c/kjogumTpOCYSB+ii7OiOvRV7pQZpfgHrD/Bo9p35hLzkaGPc8xWl/AfDkVl7q0lURAvECY9ASDQ0=
      FIBR_WEBHOOK_SECRET: AgDidDHZ5oA4g5OJAMNJhLBnPBnw45BA4oydJ9nJLJZ2TMitkJhKbGLQxcuyHaqJPVZVSrR+ioL6dlZdj9W5U5vzU/qqlIAUX4+wtAVSx4nutLRz46nOoQmBw//TtoH8txdLHn6+i/OyA9xNt2UWA5ht1ho6pf0I3eXt2TeU64f0ppt3QV4DIN/qVrjDYvgd/tF1wT5bA9R10oIVUYzc+/bSrlkBBK/h+jxPK6dm3q4NR6F7f0Ac/4OI+6okIoQaEGcIKzSgLu/Z0PMg5fV7rT8UrFI1JYGBD3mSWVKc2zegkkRLSVSvceeJuPuWwpcNLjGJyt3TE3Ma6/OcQY609nCcu00s9fyn8YrY6VLqJgbN+JNOa+dvE6CeaC1r7tuM6cQalYPntTXUnoDQD8mPATbjcF++mSe86ZxnmS4+Vs9MlIqerCETeaFfkD0H+9pt32XZdwyir/LR8pAkKKBgcaT9LE0BzyelbUsUw7DYx+yOWC4E0g6tA6RdClTzdSuuXEm2qDCjILQoex1mpzDqHzaoJlTIEhUoPFmnxNKEV+kbOCF2QEHpE/HMm9cnorJPKOgR+36L7MJmV5oSXr6UMRZBcq4KH6RuPYwQL/HI1Tbj34QmhVkmS+JXDJwdLGqkb0u0tfab7ZekTY6YYCXrhIWjD+bCGLVoecHWKcxC5/M9o6FkPdSHvKQOqQk44aDq1c8Ky6UDURm4MvccKU86xnUDtt+2wUMMlv07Hkv0hWoXalCmwaT1JRboVAPU/Ni5LadmYBTN8uv3BGH7Y0S+Qo5y8cZuED9IqxakF8u0P9/pPq6qLHQn9fTfALBk4I7W
    tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/storage
      operator: Exists
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 400m
        memory: 64Mi
    securityContext:
      runAsGroup: 1000
      runAsUser: 1000
      runAsNonRoot: true
      allowPrivilegeEscalation: false
    autoscaling:
      enabled: false
    ingress:
      enabled: true
      compress: true
      hosts:
      - fibr.vibioh.fr
    pprof:
      enabled: true
