apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fibr
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: '0.0.85'
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: fibr
    image:
      name: vibioh/fibr
      tag: '202207161620' # {"$imagepolicy": "default:flux-fibr-web:tag"}
    volumes:
      - name: data
        persistentVolumeClaim:
          claimName: fibr
      - name: tmp
        emptyDir: {}
    volumeMounts:
      - name: data
        mountPath: /data
      - name: tmp
        mountPath: /tmp
    config:
      FIBR_CHUNK_UPLOAD: 'true'
      FIBR_EXIF_DIRECT_ACCESS: 'true'
      FIBR_EXIF_URL: http://exas
      FIBR_IGNORE_PATTERN: '.st(folder|ignore)'
      FIBR_LOGGER_JSON: 'true'
      FIBR_PUBLIC_URL: https://fibr.vibioh.fr
      FIBR_SANITIZE_ON_START: 'true'
      FIBR_THUMBNAIL_DIRECT_ACCESS: 'true'
      FIBR_THUMBNAIL_LARGE_SIZE: '1000'
      FIBR_THUMBNAIL_MIN_BITRATE: '30000000'
      FIBR_THUMBNAIL_URL: http://vith
      FIBR_TRACER_URL: http://jaeger.monitoring:14268/api/traces
      OTEL_SERVICE_NAME: fibr
    secrets:
      FIBR_AMQP_URI: AgB6MBBASBJE3A/eXnICgDfQmbTaWT3B9TpmMln6TF2+rA2R3GgLlDa/NGqDw8PIF04E40u+oA8xxvsYhP/WXRubtIYLZjtwGD1SvXG+fylvcr9Beh1gWwEbu3x5pakgHRD4KOCvtOGEniKQt9gC1qOmYMxbRfZtXaONA/mbvSimP7oqyINPXgIoX/5sgw6X1+kIe0cCYNr8v+gL1dsaC7Y1OOxSav4UD0H2AjEd2271INxcq4ry2KLC8Ra8SnE+bcfMhnvnv7lTxGY8OWDz+6/F/kRwPFEvuz2IX1Zq7iGMhizTlOCqJUZT6N28WgOcQ6HkF8swWuAfF0IcBpIXxTu0YUqbYPpcyGyxEJld4yUP5m8EQhpZChNBXTERadojrDwCTOcJx/fPkej5/+r8OAwFfUAI4tvfyjWXAXUckGW1ZNrdPgeWSXmEIDQoWKRU/reY1RshAV39jr6YMtmrUQ/ryRm8f3DAIlQSgk/DdZf+D1aI1x07aIyum7KNpY3GJ5VQLObFV6eXSiVPTR5BL9HcLH4XgOOG9PWcVnbyIxwf8S/FibynmPlgQ6rYz1ZLGedYrs1X4SfEyErKPenNsRru+5YZdEckaJN5CDXCRGTP8xlrW6fwfYmbq2wtNIlFNnci+tY5SrGS7AvCY6Fj1eZ8bw8d6Xd1KttQ+h/0V2F6f5iHTpDLbT3ehaYDQcjF48xkS0cwzcu+Nl8MuG7gD5u9lHAmPhjYsOrb+Bue8EpNMFr6I5ZLg29H14pyZ1D+/zNq6V4=
      FIBR_AUTH_USERS: AgBEhkIPEsyIu3s/xQEBREyNhXy2dXJccLENT77Jx4m01pbB8WPDh3w3LEEQ5hb4CKVkzMFs53jL0Z6ZWweQCJ44k300MJWP+EGCmfdiZC/15T/pFdnPd5qhd3FWwGiBmEKkE23RF8mRW70f1OaNQ7lJ87W+NFDdGHILXPJiCMld6dRS5B5ruO9E8nrvBINvof3yLN4CIjlwTKBpgbLfq7sAdfeP17Hgv2uDJKO1YhLyRzXA7FHF4ikMQ779+S2QQvHrMkwpgbpwAwXOwmanFlNKCEBmw1GpE5qSO2LHmiGdro9dNjbKd+L3VqVb+luNM7m1zc0/KwoCljh0/BbKZ1kETPgECY3ypiJ4UrGvmq2ASwEDaA/CgAFIO+ktKz7PvBWM3f10xLmPO+t99BFCHxUMdcYe7TyhPoWFsn8D2Dk8g7guyXxDqMk8gxWxJ7Fqk4iu7vI6DklCHk4nttaYmNH0nZrBSF8OOogdV0DMfMvus8wDIg67a8GwIWqU3rKcnV1K5Me/vQTUo5WAWwfzugtyiTbG+ssOzrpgK847J55JlzbLJmgcoebAtyqxAVxXv7jL919ifnMUzD28hJxvMz/Kz2dJJ3xZgljoyNqWnMrUt4NPMX9dDPz6HWA9OF4CjdQU+beWBX6dbRCrKRlLWQwP73r+ATagMov1TGBUb2LUCfKP9Ee3A1YwGbgB+UCJE1OSpypRwGyF/3hM9sxM8gtuJDBhyTbHQaf54lGvDJZ/Tc2qvpjfVTFyuBjd/o8r7HBMwGWhq4WrOtbWBxA14DgaRe/APS0=
      FIBR_WEBHOOK_SECRET: AgC5qdnLQUXxWwRDhPPXutN8OTeBGe1t/e9uj3Mu55jL89pSvBLO2gUXclUjV9kpNIL9cgtsnpbtyOy/cQ+xzNe8iI1kawzXuzJ/4q5q2GLVra/JT5aSrHnSnpS7vVOivmLNCHksRDuM7vQn8Pi2WIYxe/nOJITv2DDLyG2nYt+FQwC89Uy0uxBtlbHz28Vdkfh3A3wH0nB+xf2EXqyCkmSklqSmRHSQUq1PFKvXrBaMQpzK2QOlLNKBRs70YqRxft3uCnBN8fEI4Uyc3rpsovfYLBP+iQRqXg1ZYBnneBnEvsThF3f5K0KXv72mYe/DKbUV6TaBbvoXGX8sqEteXkW0RV9AhWyWS+1U3mP/oS17LJuVu/ZaWwM4pgyK4oNTfdXRk1hOxeZVga/R9F7CZXV/ts1fcUV5+pZtvOtO7yOTAwxQlzu8DS/AnZcYhEflyv8AvSytCHt5/7BL0IKNVIq5dayxQRvfc9os6LaMtvn+TUjrEf3a0cqf24s3ZvF6LBv2njQC3zkOIDeA98YRzRiBcpNhONu9JIITbtWTDfbFWVWbsMgY6NlmR9oIiyq68YEgl3TyTVaJUWT4/dbUTRMnySKowYqQGA/dnlAitQPpbfxZo9Hx0dAWuDeXMnmKW7BbeFRe1I7ge/vGB1qzGstFbQCQo3SnETRE4cAMfRAiocxcRzJ6WtEXLqu6O4tJNONVrW5NIX5ayy4i3B87Z2oB1Jjq+55C9zIR7Uc6tLq5SVYhUHTU1Q95reGDsrmOWja8TkBXgmzdMQOP0WfiV5NhxYKlff8jUCfLsmkk4bguY0LIN/0n0EzGxTIK4ev5
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/storage
        operator: Exists
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 400m
        memory: 64Mi
    securityContext:
      runAsGroup: 1000
      runAsUser: 1000
      runAsNonRoot: true
      allowPrivilegeEscalation: false
    autoscaling:
      enabled: false
    ingress:
      enabled: true
      compress: true
      sticky: true
      hosts:
        - fibr.vibioh.fr
    pprof:
      enabled: true
