#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

HTTP_STATUS=$(curl -X POST -u "${DEPLOY_CREDENTIALS}" -o output.txt -w "%{http_code}" "https://deploy.vibioh.fr/${1}/${2}/" --data-binary "${3}")

cat output.txt

if [[ "${HTTP_STATUS}" != "200" ]]; then
   exit 1
fi
