#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

readonly OUTPUT_TXT="output.txt"

main() {
  HTTP_STATUS=$(curl -X POST -u "${DEPLOY_CREDENTIALS}" -o "${OUTPUT_TXT}" -w "%{http_code}" "https://deploy.vibioh.fr/${1}/${2}/" --data-binary "${3}")

  cat "${OUTPUT_TXT}"
  rm "${OUTPUT_TXT}"

  if [[ "${HTTP_STATUS}" != "200" ]]; then
     exit 1
  fi
}

main "${@}"
